In [26]:
a = [[1,2]]*2
c = a + [a[-1]]*3
print(c)

[[1, 2], [1, 2], [1, 2], [1, 2], [1, 2]]


In [3]:
import  torch
width = 5
height = width
state = torch.zeros((width, height))
print(state)
body = torch.tensor([[1,1],[1,2],[1,3]])
print(body[0])

state[tuple(body)] = 5
print(state)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([1, 1])


IndexError: too many indices for tensor of dimension 2

In [43]:
[state[tuple(i)] for i in body]

for block in body:
    state[tuple(block)] = 11

state

tensor([[ 0.,  0.,  0.,  0.,  0.],
        [ 0., 11., 11., 11.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [67]:
from pygame.math import Vector2 as vc
import numpy as np
direction = vc([0,1])#.transpose()
print('Original vector: ', direction)
print('rotation toward right')
rotation = np.array([[0,1],[-1,0]])
#print(rotation)
new_dir = np.matmul(rotation,direction)
print(new_dir)


print('rotation toward left')
rotation = np.array([[0,-1],[1,0]])
#print(rotation)
new_dir = np.matmul(rotation,direction)
new_dir = vc(new_dir.tolist())
print(new_dir)

Original vector:  [0, 1]
rotation toward right
[1. 0.]
rotation toward left
[-1, 0]


In [68]:
a = [1,3,4]
a[-1]

4

In [14]:
c = torch.tensor([[1],[2]])

In [16]:
from dqn_tools import save_h5_dataset
torch.add(c, c)
print(c)
save_h5_dataset(c,'data/ccc')

tensor([[1],
        [2]])
Dataset : data/ccc                  shape : torch.Size([2, 1])     size :    0.0 Mo   (saved)


In [22]:
torch.tensor([5]) in c

False

In [40]:
from dqn_tools import load_h5_dataset
import  torch

states, actions , _, _, _ = load_h5_dataset('data/2021-04-05_08h50m09s.h5')
states = torch.tensor(states[0:10]).tolist()
actions = torch.tensor(actions[0:10]).tolist()
state, action= states[0], actions[9]
states_actions = list(zip(states, actions))

#check if

ans  = (state,action) in states_actions
ans

False

In [ ]:
print(states_actions[0:2])

In [41]:
l = [ ([1, 2], [5]) , ([0, 0],[0]) ]
([1, 2], [0]) in l

False

In [49]:
A = [0,1,2]
ae = [2]
print(A)

[0, 1, 2]


In [60]:
[1,2]  != []

True

In [62]:
a= 1
a+= True
a

2

In [65]:
import numpy as n
t = n.log(0.05/.9)/0.00005
t


-57807.43515792329

In [6]:
a = [1,2,3,4]
c = [2,3]
b = [a[i] for i in c]
b

[3, 4]

In [2]:
100000/3.5

28571.428571428572

In [45]:
import  random
for i in range(10):
    #random.seed(i)
    print(random.randint(0,10))


8
8
8
8
10
9
9
6
4
3


In [24]:
a = random.getstate()
print(random.randint(1,10))

5


In [22]:
random.setstate(a)
print(random.randint(1,10))

3


In [28]:
type(random.getstate())


tuple

In [5]:
100/14.285714149475098


7.000000066757202

In [7]:
a = (1, 2)
a[0]

1

In [12]:
for i in range(2) :
    for j in range(3):
        print(i, j)

0 0
0 1
0 2
1 0
1 1
1 2


In [27]:
[i for i in range(3)]

[0, 1, 2]

In [26]:
a = [1,2,34,'a']

for i,j in enumerate(a):
    print(i,j)

0 1
1 2
2 34
3 a


In [28]:
15000/254


59.05511811023622